### ISSUE TITLE
这是什么问题 版本0.0.12

### ISSUE THREAD

**Issue by NHQAQ** [GraiaProject/Saya#5]
我单独运行的module下的PetPet的__init__.py
Traceback (most recent call last):
  File "/Users/nanhai/PycharmProjects/saya_plugins_collection/modules/PetPet/__init__.py", line 27, in <module>
    saya = Saya.current()
  File "/Users/nanhai/PycharmProjects/saya_plugins_collection/venv/lib/python3.8/site-packages/graia/saya/__init__.py", line 59, in current
    return saya_instance.get()
LookupError: <ContextVar name='saya_instance' at 0x12258dae0>

**Comment by NHQAQ** [comment]
直接运行main.py还会报错
Traceback (most recent call last):
  File "/Users/nanhai/PycharmProjects/saya_plugins_collection/main.py", line 16, in <module>
    configs = load_config()
  File "/Users/nanhai/PycharmProjects/saya_plugins_collection/utils.py", line 18, in load_config
    with open(config_file, 'r', encoding='utf-8') as f:  # 从json读配置
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by BlueGlassBlock** [comment]
> 直接运行main.py还会报错 Traceback (most recent call last): File "/Users/nanhai/PycharmProjects/saya_plugins_collection/main.py", line 16, in configs = load_config() File "/Users/nanhai/PycharmProjects/saya_plugins_collection/utils.py", line 18, in load_config with open(config_file, 'r', encoding='utf-8') as f: # 从json读配置 FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

你没创建 `config.json`

**Comment by BlueGlassBlock** [comment]
> 我单独运行的module下的PetPet的__init__.py Traceback (most recent call last): File "/Users/nanhai/PycharmProjects/saya_plugins_collection/modules/PetPet/**init**.py", line 27, in saya = Saya.current() File "/Users/nanhai/PycharmProjects/saya_plugins_collection/venv/lib/python3.8/site-packages/graia/saya/**init**.py", line 59, in current return saya_instance.get() LookupError: <ContextVar name='saya_instance' at 0x12258dae0>

需要 `with saya.module_context()` 注入 `Saya` 与 `Channel` 实例 你单独运行当然跑不了了
